# neutral_sites.py
# Database of neutral site cities for College Hoops Sim.
# Used for tournament events, standalone neutral games, and crowd split calculations.
#
# Atmosphere tiers:
#   marquee  - Elite venues, massive capacity, national TV draw (Madison Square Garden, United Center, etc.)
#   major    - Large markets, big arenas, strong college basketball history
#   mid      - Mid-size markets, real tournament hosts, solid atmospheres
#   small    - Smaller venues, regional events, boutique tournament feel
#
# capacity: approximate arena capacity for basketball
# region: geographic region for scheduling diversity logic

NEUTRAL_SITES = {

    # --- MARQUEE TIER ---

    'new_york_ny': {
        'city': 'New York',
        'state': 'NY',
        'latitude': 40.7505,
        'longitude': -73.9934,
        'arena': 'Madison Square Garden',
        'capacity': 19812,
        'tier': 'marquee',
        'region': 'northeast',
    },
    'chicago_il': {
        'city': 'Chicago',
        'state': 'IL',
        'latitude': 41.8807,
        'longitude': -87.6742,
        'arena': 'United Center',
        'capacity': 20917,
        'tier': 'marquee',
        'region': 'midwest',
    },
    'los_angeles_ca': {
        'city': 'Los Angeles',
        'state': 'CA',
        'latitude': 34.0430,
        'longitude': -118.2673,
        'arena': 'Crypto.com Arena',
        'capacity': 19079,
        'tier': 'marquee',
        'region': 'west',
    },
    'dallas_tx': {
        'city': 'Dallas',
        'state': 'TX',
        'latitude': 32.7905,
        'longitude': -96.8103,
        'arena': 'American Airlines Center',
        'capacity': 19200,
        'tier': 'marquee',
        'region': 'south',
    },
    'atlanta_ga': {
        'city': 'Atlanta',
        'state': 'GA',
        'latitude': 33.7573,
        'longitude': -84.3963,
        'arena': 'State Farm Arena',
        'capacity': 21000,
        'tier': 'marquee',
        'region': 'southeast',
    },
    'houston_tx': {
        'city': 'Houston',
        'state': 'TX',
        'latitude': 29.7508,
        'longitude': -95.3621,
        'arena': 'Toyota Center',
        'capacity': 18300,
        'tier': 'marquee',
        'region': 'south',
    },
    'washington_dc': {
        'city': 'Washington',
        'state': 'DC',
        'latitude': 38.8981,
        'longitude': -77.0209,
        'arena': 'Capital One Arena',
        'capacity': 20356,
        'tier': 'marquee',
        'region': 'mid_atlantic',
    },
    'miami_fl': {
        'city': 'Miami',
        'state': 'FL',
        'latitude': 25.7814,
        'longitude': -80.1870,
        'arena': 'Kaseya Center',
        'capacity': 19600,
        'tier': 'marquee',
        'region': 'southeast',
    },
    'phoenix_az': {
        'city': 'Phoenix',
        'state': 'AZ',
        'latitude': 33.4457,
        'longitude': -112.0712,
        'arena': 'Footprint Center',
        'capacity': 18422,
        'tier': 'marquee',
        'region': 'west',
    },
    'boston_ma': {
        'city': 'Boston',
        'state': 'MA',
        'latitude': 42.3662,
        'longitude': -71.0621,
        'arena': 'TD Garden',
        'capacity': 19156,
        'tier': 'marquee',
        'region': 'northeast',
    },
    'minneapolis_mn': {
        'city': 'Minneapolis',
        'state': 'MN',
        'latitude': 44.9795,
        'longitude': -93.2762,
        'arena': 'Target Center',
        'capacity': 18978,
        'tier': 'marquee',
        'region': 'midwest',
    },
    'san_francisco_ca': {
        'city': 'San Francisco',
        'state': 'CA',
        'latitude': 37.7680,
        'longitude': -122.3877,
        'arena': 'Chase Center',
        'capacity': 18064,
        'tier': 'marquee',
        'region': 'west',
    },
    'portland_or': {
        'city': 'Portland',
        'state': 'OR',
        'latitude': 45.5316,
        'longitude': -122.6668,
        'arena': 'Moda Center',
        'capacity': 19393,
        'tier': 'marquee',
        'region': 'northwest',
    },
    'denver_co': {
        'city': 'Denver',
        'state': 'CO',
        'latitude': 39.7487,
        'longitude': -104.9820,
        'arena': 'Ball Arena',
        'capacity': 19520,
        'tier': 'marquee',
        'region': 'west',
    },
    'new_orleans_la': {
        'city': 'New Orleans',
        'state': 'LA',
        'latitude': 29.9490,
        'longitude': -90.0812,
        'arena': 'Smoothie King Center',
        'capacity': 17791,
        'tier': 'marquee',
        'region': 'south',
    },
    'indianapolis_in': {
        'city': 'Indianapolis',
        'state': 'IN',
        'latitude': 39.7640,
        'longitude': -86.1555,
        'arena': 'Gainbridge Fieldhouse',
        'capacity': 17923,
        'tier': 'marquee',
        'region': 'midwest',
    },
    'las_vegas_nv': {
        'city': 'Las Vegas',
        'state': 'NV',
        'latitude': 36.1088,
        'longitude': -115.1783,
        'arena': 'T-Mobile Arena',
        'capacity': 20000,
        'tier': 'marquee',
        'region': 'west',
    },

    # --- MAJOR TIER ---

    'charlotte_nc': {
        'city': 'Charlotte',
        'state': 'NC',
        'latitude': 35.2251,
        'longitude': -80.8392,
        'arena': 'Spectrum Center',
        'capacity': 19077,
        'tier': 'major',
        'region': 'southeast',
    },
    'orlando_fl': {
        'city': 'Orlando',
        'state': 'FL',
        'latitude': 28.5392,
        'longitude': -81.3836,
        'arena': 'Kia Center',
        'capacity': 18846,
        'tier': 'major',
        'region': 'southeast',
    },
    'detroit_mi': {
        'city': 'Detroit',
        'state': 'MI',
        'latitude': 42.3410,
        'longitude': -83.0550,
        'arena': 'Little Caesars Arena',
        'capacity': 19515,
        'tier': 'major',
        'region': 'midwest',
    },
    'cleveland_oh': {
        'city': 'Cleveland',
        'state': 'OH',
        'latitude': 41.4965,
        'longitude': -81.6882,
        'arena': 'Rocket Mortgage FieldHouse',
        'capacity': 19432,
        'tier': 'major',
        'region': 'midwest',
    },
    'philadelphia_pa': {
        'city': 'Philadelphia',
        'state': 'PA',
        'latitude': 39.9012,
        'longitude': -75.1720,
        'arena': 'Wells Fargo Center',
        'capacity': 20478,
        'tier': 'major',
        'region': 'mid_atlantic',
    },
    'memphis_tn': {
        'city': 'Memphis',
        'state': 'TN',
        'latitude': 35.1382,
        'longitude': -90.0505,
        'arena': 'FedExForum',
        'capacity': 18119,
        'tier': 'major',
        'region': 'south',
    },
    'nashville_tn': {
        'city': 'Nashville',
        'state': 'TN',
        'latitude': 36.1591,
        'longitude': -86.7785,
        'arena': 'Bridgestone Arena',
        'capacity': 17159,
        'tier': 'major',
        'region': 'south',
    },
    'san_antonio_tx': {
        'city': 'San Antonio',
        'state': 'TX',
        'latitude': 29.4270,
        'longitude': -98.4375,
        'arena': 'Frost Bank Center',
        'capacity': 18418,
        'tier': 'major',
        'region': 'south',
    },
    'seattle_wa': {
        'city': 'Seattle',
        'state': 'WA',
        'latitude': 47.6220,
        'longitude': -122.3541,
        'arena': 'Climate Pledge Arena',
        'capacity': 17100,
        'tier': 'major',
        'region': 'northwest',
    },
    'kansas_city_mo': {
        'city': 'Kansas City',
        'state': 'MO',
        'latitude': 39.0989,
        'longitude': -94.5786,
        'arena': 'T-Mobile Center',
        'capacity': 19500,
        'tier': 'major',
        'region': 'midwest',
    },
    'sacramento_ca': {
        'city': 'Sacramento',
        'state': 'CA',
        'latitude': 38.5802,
        'longitude': -121.4997,
        'arena': 'Golden 1 Center',
        'capacity': 17583,
        'tier': 'major',
        'region': 'west',
    },
    'salt_lake_city_ut': {
        'city': 'Salt Lake City',
        'state': 'UT',
        'latitude': 40.7683,
        'longitude': -111.9011,
        'arena': 'Delta Center',
        'capacity': 18306,
        'tier': 'major',
        'region': 'west',
    },
    'oklahoma_city_ok': {
        'city': 'Oklahoma City',
        'state': 'OK',
        'latitude': 35.4634,
        'longitude': -97.5151,
        'arena': 'Paycom Center',
        'capacity': 18203,
        'tier': 'major',
        'region': 'south',
    },
    'san_diego_ca': {
        'city': 'San Diego',
        'state': 'CA',
        'latitude': 32.7108,
        'longitude': -117.1598,
        'arena': 'Pechanga Arena',
        'capacity': 14200,
        'tier': 'major',
        'region': 'west',
    },
    'pittsburgh_pa': {
        'city': 'Pittsburgh',
        'state': 'PA',
        'latitude': 40.4396,
        'longitude': -79.9763,
        'arena': 'PPG Paints Arena',
        'capacity': 18387,
        'tier': 'major',
        'region': 'mid_atlantic',
    },
    'st_louis_mo': {
        'city': 'St. Louis',
        'state': 'MO',
        'latitude': 38.6270,
        'longitude': -90.2028,
        'arena': 'Enterprise Center',
        'capacity': 18096,
        'tier': 'major',
        'region': 'midwest',
    },
    'baltimore_md': {
        'city': 'Baltimore',
        'state': 'MD',
        'latitude': 39.2841,
        'longitude': -76.6218,
        'arena': 'CFG Bank Arena',
        'capacity': 14000,
        'tier': 'major',
        'region': 'mid_atlantic',
    },
    'raleigh_nc': {
        'city': 'Raleigh',
        'state': 'NC',
        'latitude': 35.8031,
        'longitude': -78.7220,
        'arena': 'PNC Arena',
        'capacity': 18680,
        'tier': 'major',
        'region': 'southeast',
    },
    'jacksonville_fl': {
        'city': 'Jacksonville',
        'state': 'FL',
        'latitude': 30.3322,
        'longitude': -81.6557,
        'arena': 'VyStar Veterans Memorial Arena',
        'capacity': 15000,
        'tier': 'major',
        'region': 'southeast',
    },
    'columbus_oh': {
        'city': 'Columbus',
        'state': 'OH',
        'latitude': 39.9690,
        'longitude': -82.9971,
        'arena': 'Nationwide Arena',
        'capacity': 18500,
        'tier': 'major',
        'region': 'midwest',
    },
    'louisville_ky': {
        'city': 'Louisville',
        'state': 'KY',
        'latitude': 38.2186,
        'longitude': -85.7546,
        'arena': 'KFC Yum! Center',
        'capacity': 22090,
        'tier': 'major',
        'region': 'south',
    },
    'cincinnati_oh': {
        'city': 'Cincinnati',
        'state': 'OH',
        'latitude': 39.1031,
        'longitude': -84.5120,
        'arena': 'Heritage Bank Center',
        'capacity': 17556,
        'tier': 'major',
        'region': 'midwest',
    },
    'buffalo_ny': {
        'city': 'Buffalo',
        'state': 'NY',
        'latitude': 42.8749,
        'longitude': -78.8759,
        'arena': 'KeyBank Center',
        'capacity': 19070,
        'tier': 'major',
        'region': 'northeast',
    },
    'richmond_va': {
        'city': 'Richmond',
        'state': 'VA',
        'latitude': 37.5407,
        'longitude': -77.4360,
        'arena': 'Altria Theater',
        'capacity': 3500,
        'tier': 'major',
        'region': 'mid_atlantic',
    },
    'hartford_ct': {
        'city': 'Hartford',
        'state': 'CT',
        'latitude': 41.7658,
        'longitude': -72.6851,
        'arena': 'XL Center',
        'capacity': 15635,
        'tier': 'major',
        'region': 'northeast',
    },
    'milwaukee_wi': {
        'city': 'Milwaukee',
        'state': 'WI',
        'latitude': 43.0451,
        'longitude': -87.9170,
        'arena': 'Fiserv Forum',
        'capacity': 17341,
        'tier': 'major',
        'region': 'midwest',
    },
    'omaha_ne': {
        'city': 'Omaha',
        'state': 'NE',
        'latitude': 41.2565,
        'longitude': -95.9345,
        'arena': 'CHI Health Center',
        'capacity': 17560,
        'tier': 'major',
        'region': 'midwest',
    },
    'tucson_az': {
        'city': 'Tucson',
        'state': 'AZ',
        'latitude': 32.2319,
        'longitude': -110.9501,
        'arena': 'McKale Center',
        'capacity': 14644,
        'tier': 'major',
        'region': 'west',
    },
    'albuquerque_nm': {
        'city': 'Albuquerque',
        'state': 'NM',
        'latitude': 35.0853,
        'longitude': -106.6500,
        'arena': 'Tingley Coliseum',
        'capacity': 11500,
        'tier': 'major',
        'region': 'west',
    },
    'spokane_wa': {
        'city': 'Spokane',
        'state': 'WA',
        'latitude': 47.6588,
        'longitude': -117.4260,
        'arena': 'Spokane Arena',
        'capacity': 12600,
        'tier': 'major',
        'region': 'northwest',
    },
    'birmingham_al': {
        'city': 'Birmingham',
        'state': 'AL',
        'latitude': 33.5207,
        'longitude': -86.8025,
        'arena': 'Legacy Arena',
        'capacity': 17500,
        'tier': 'major',
        'region': 'southeast',
    },
    'greenville_sc': {
        'city': 'Greenville',
        'state': 'SC',
        'latitude': 34.8526,
        'longitude': -82.3940,
        'arena': 'Bon Secours Wellness Arena',
        'capacity': 16000,
        'tier': 'major',
        'region': 'southeast',
    },

    # --- MID TIER ---

    'anchorage_ak': {
        'city': 'Anchorage',
        'state': 'AK',
        'latitude': 61.2181,
        'longitude': -149.9003,
        'arena': 'Alaska Airlines Center',
        'capacity': 8500,
        'tier': 'mid',
        'region': 'northwest',
    },
    'honolulu_hi': {
        'city': 'Honolulu',
        'state': 'HI',
        'latitude': 21.2969,
        'longitude': -157.8583,
        'arena': 'SimpliFi Arena',
        'capacity': 8800,
        'tier': 'mid',
        'region': 'west',
    },
    'boise_id': {
        'city': 'Boise',
        'state': 'ID',
        'latitude': 43.6187,
        'longitude': -116.2146,
        'arena': 'ExtraMile Arena',
        'capacity': 12500,
        'tier': 'mid',
        'region': 'northwest',
    },
    'el_paso_tx': {
        'city': 'El Paso',
        'state': 'TX',
        'latitude': 31.7619,
        'longitude': -106.4850,
        'arena': 'Don Haskins Center',
        'capacity': 12222,
        'tier': 'mid',
        'region': 'south',
    },
    'sioux_falls_sd': {
        'city': 'Sioux Falls',
        'state': 'SD',
        'latitude': 43.5446,
        'longitude': -96.7311,
        'arena': 'Denny Sanford Premier Center',
        'capacity': 12000,
        'tier': 'mid',
        'region': 'midwest',
    },
    'fargo_nd': {
        'city': 'Fargo',
        'state': 'ND',
        'latitude': 46.8772,
        'longitude': -96.7898,
        'arena': 'Fargodome',
        'capacity': 6000,
        'tier': 'mid',
        'region': 'midwest',
    },
    'bismarck_nd': {
        'city': 'Bismarck',
        'state': 'ND',
        'latitude': 46.8083,
        'longitude': -100.7837,
        'arena': 'Bismarck Event Center',
        'capacity': 7000,
        'tier': 'mid',
        'region': 'midwest',
    },
    'billings_mt': {
        'city': 'Billings',
        'state': 'MT',
        'latitude': 45.7833,
        'longitude': -108.5007,
        'arena': 'First Interstate Arena',
        'capacity': 12000,
        'tier': 'mid',
        'region': 'northwest',
    },
    'cheyenne_wy': {
        'city': 'Cheyenne',
        'state': 'WY',
        'latitude': 41.1400,
        'longitude': -104.8202,
        'arena': 'Cheyenne Ice and Events Center',
        'capacity': 6000,
        'tier': 'mid',
        'region': 'west',
    },
    'columbia_sc': {
        'city': 'Columbia',
        'state': 'SC',
        'latitude': 33.9946,
        'longitude': -81.0300,
        'arena': 'Colonial Life Arena',
        'capacity': 18000,
        'tier': 'mid',
        'region': 'southeast',
    },
    'knoxville_tn': {
        'city': 'Knoxville',
        'state': 'TN',
        'latitude': 35.9544,
        'longitude': -83.9268,
        'arena': 'Thompson-Boling Arena',
        'capacity': 21678,
        'tier': 'mid',
        'region': 'southeast',
    },
    'baton_rouge_la': {
        'city': 'Baton Rouge',
        'state': 'LA',
        'latitude': 30.4133,
        'longitude': -91.1800,
        'arena': 'Pete Maravich Assembly Center',
        'capacity': 13472,
        'tier': 'mid',
        'region': 'south',
    },
    'little_rock_ar': {
        'city': 'Little Rock',
        'state': 'AR',
        'latitude': 34.7465,
        'longitude': -92.2896,
        'arena': 'Simmons Bank Arena',
        'capacity': 18000,
        'tier': 'mid',
        'region': 'south',
    },
    'jackson_ms': {
        'city': 'Jackson',
        'state': 'MS',
        'latitude': 32.2988,
        'longitude': -90.1848,
        'arena': 'Mississippi Coliseum',
        'capacity': 8000,
        'tier': 'mid',
        'region': 'south',
    },
    'huntsville_al': {
        'city': 'Huntsville',
        'state': 'AL',
        'latitude': 34.7304,
        'longitude': -86.5861,
        'arena': 'Von Braun Center',
        'capacity': 8000,
        'tier': 'mid',
        'region': 'southeast',
    },
    'lexington_ky': {
        'city': 'Lexington',
        'state': 'KY',
        'latitude': 38.0406,
        'longitude': -84.5037,
        'arena': 'Rupp Arena',
        'capacity': 20545,
        'tier': 'mid',
        'region': 'south',
    },
    'champaign_il': {
        'city': 'Champaign',
        'state': 'IL',
        'latitude': 40.1164,
        'longitude': -88.2434,
        'arena': 'State Farm Center',
        'capacity': 15544,
        'tier': 'mid',
        'region': 'midwest',
    },
    'fort_worth_tx': {
        'city': 'Fort Worth',
        'state': 'TX',
        'latitude': 32.7555,
        'longitude': -97.3308,
        'arena': 'Dickies Arena',
        'capacity': 14000,
        'tier': 'mid',
        'region': 'south',
    },
    'austin_tx': {
        'city': 'Austin',
        'state': 'TX',
        'latitude': 30.2849,
        'longitude': -97.7341,
        'arena': 'Moody Center',
        'capacity': 15000,
        'tier': 'mid',
        'region': 'south',
    },
    'wichita_ks': {
        'city': 'Wichita',
        'state': 'KS',
        'latitude': 37.6872,
        'longitude': -97.3301,
        'arena': 'INTRUST Bank Arena',
        'capacity': 15004,
        'tier': 'mid',
        'region': 'midwest',
    },
    'tulsa_ok': {
        'city': 'Tulsa',
        'state': 'OK',
        'latitude': 36.1540,
        'longitude': -95.9928,
        'arena': 'BOK Center',
        'capacity': 19199,
        'tier': 'mid',
        'region': 'south',
    },
    'lubbock_tx': {
        'city': 'Lubbock',
        'state': 'TX',
        'latitude': 33.5779,
        'longitude': -101.8552,
        'arena': 'United Supermarkets Arena',
        'capacity': 15098,
        'tier': 'mid',
        'region': 'south',
    },
    'reno_nv': {
        'city': 'Reno',
        'state': 'NV',
        'latitude': 39.5296,
        'longitude': -119.8138,
        'arena': 'Lawlor Events Center',
        'capacity': 11200,
        'tier': 'mid',
        'region': 'west',
    },
    'fresno_ca': {
        'city': 'Fresno',
        'state': 'CA',
        'latitude': 36.7378,
        'longitude': -119.7871,
        'arena': 'Save Mart Center',
        'capacity': 15596,
        'tier': 'mid',
        'region': 'west',
    },
    'colorado_springs_co': {
        'city': 'Colorado Springs',
        'state': 'CO',
        'latitude': 38.8339,
        'longitude': -104.8214,
        'arena': 'Broadmoor World Arena',
        'capacity': 8500,
        'tier': 'mid',
        'region': 'west',
    },
    'columbia_mo': {
        'city': 'Columbia',
        'state': 'MO',
        'latitude': 38.9517,
        'longitude': -92.3341,
        'arena': 'Mizzou Arena',
        'capacity': 15061,
        'tier': 'mid',
        'region': 'midwest',
    },
    'lincoln_ne': {
        'city': 'Lincoln',
        'state': 'NE',
        'latitude': 40.8136,
        'longitude': -96.7026,
        'arena': 'Pinnacle Bank Arena',
        'capacity': 15500,
        'tier': 'mid',
        'region': 'midwest',
    },
    'des_moines_ia': {
        'city': 'Des Moines',
        'state': 'IA',
        'latitude': 41.5868,
        'longitude': -93.6250,
        'arena': 'Wells Fargo Arena',
        'capacity': 17122,
        'tier': 'mid',
        'region': 'midwest',
    },
    'madison_wi': {
        'city': 'Madison',
        'state': 'WI',
        'latitude': 43.0731,
        'longitude': -89.4012,
        'arena': 'Kohl Center',
        'capacity': 17142,
        'tier': 'mid',
        'region': 'midwest',
    },
    'rochester_ny': {
        'city': 'Rochester',
        'state': 'NY',
        'latitude': 43.1566,
        'longitude': -77.6088,
        'arena': 'Blue Cross Arena',
        'capacity': 12695,
        'tier': 'mid',
        'region': 'northeast',
    },
    'albany_ny': {
        'city': 'Albany',
        'state': 'NY',
        'latitude': 42.6526,
        'longitude': -73.7562,
        'arena': 'MVP Arena',
        'capacity': 15500,
        'tier': 'mid',
        'region': 'northeast',
    },
    'providence_ri': {
        'city': 'Providence',
        'state': 'RI',
        'latitude': 41.8240,
        'longitude': -71.4128,
        'arena': 'Amica Mutual Pavilion',
        'capacity': 14000,
        'tier': 'mid',
        'region': 'northeast',
    },
    'portland_me': {
        'city': 'Portland',
        'state': 'ME',
        'latitude': 43.6591,
        'longitude': -70.2568,
        'arena': 'Cross Insurance Arena',
        'capacity': 7800,
        'tier': 'mid',
        'region': 'northeast',
    },
    'norfolk_va': {
        'city': 'Norfolk',
        'state': 'VA',
        'latitude': 36.8508,
        'longitude': -76.2859,
        'arena': 'Chartway Arena',
        'capacity': 8000,
        'tier': 'mid',
        'region': 'mid_atlantic',
    },
    'charleston_sc': {
        'city': 'Charleston',
        'state': 'SC',
        'latitude': 32.7765,
        'longitude': -79.9311,
        'arena': 'North Charleston Coliseum',
        'capacity': 13000,
        'tier': 'mid',
        'region': 'southeast',
    },
    'shreveport_la': {
        'city': 'Shreveport',
        'state': 'LA',
        'latitude': 32.5252,
        'longitude': -93.7502,
        'arena': 'Hirsch Memorial Coliseum',
        'capacity': 10000,
        'tier': 'mid',
        'region': 'south',
    },
    'pensacola_fl': {
        'city': 'Pensacola',
        'state': 'FL',
        'latitude': 30.4213,
        'longitude': -87.2169,
        'arena': 'Pensacola Bay Center',
        'capacity': 10000,
        'tier': 'mid',
        'region': 'southeast',
    },
    'tallahassee_fl': {
        'city': 'Tallahassee',
        'state': 'FL',
        'latitude': 30.4419,
        'longitude': -84.2985,
        'arena': 'Donald L. Tucker Center',
        'capacity': 12500,
        'tier': 'mid',
        'region': 'southeast',
    },
    'springfield_mo': {
        'city': 'Springfield',
        'state': 'MO',
        'latitude': 37.2090,
        'longitude': -93.2923,
        'arena': 'Great Southern Bank Arena',
        'capacity': 11000,
        'tier': 'mid',
        'region': 'midwest',
    },
    'grand_rapids_mi': {
        'city': 'Grand Rapids',
        'state': 'MI',
        'latitude': 42.9634,
        'longitude': -85.6681,
        'arena': 'Van Andel Arena',
        'capacity': 12000,
        'tier': 'mid',
        'region': 'midwest',
    },
    'fort_wayne_in': {
        'city': 'Fort Wayne',
        'state': 'IN',
        'latitude': 41.1306,
        'longitude': -85.1294,
        'arena': 'Allen County War Memorial Coliseum',
        'capacity': 13000,
        'tier': 'mid',
        'region': 'midwest',
    },

    # --- SMALL TIER ---

    'dayton_oh': {
        'city': 'Dayton',
        'state': 'OH',
        'latitude': 39.7589,
        'longitude': -84.1916,
        'arena': 'UD Arena',
        'capacity': 13407,
        'tier': 'small',
        'region': 'midwest',
    },
    'spokane_valley_wa': {
        'city': 'Spokane Valley',
        'state': 'WA',
        'latitude': 47.6732,
        'longitude': -117.2394,
        'arena': 'Spokane Valley Arena',
        'capacity': 6000,
        'tier': 'small',
        'region': 'northwest',
    },
    'erie_pa': {
        'city': 'Erie',
        'state': 'PA',
        'latitude': 42.1292,
        'longitude': -80.0851,
        'arena': 'Erie Insurance Arena',
        'capacity': 7400,
        'tier': 'small',
        'region': 'mid_atlantic',
    },
    'peoria_il': {
        'city': 'Peoria',
        'state': 'IL',
        'latitude': 40.6936,
        'longitude': -89.5890,
        'arena': 'Carver Arena',
        'capacity': 11495,
        'tier': 'small',
        'region': 'midwest',
    },
    'evansville_in': {
        'city': 'Evansville',
        'state': 'IN',
        'latitude': 37.9748,
        'longitude': -87.5558,
        'arena': 'Ford Center',
        'capacity': 11000,
        'tier': 'small',
        'region': 'midwest',
    },
    'cedar_rapids_ia': {
        'city': 'Cedar Rapids',
        'state': 'IA',
        'latitude': 41.9779,
        'longitude': -91.6656,
        'arena': 'Alliant Energy PowerHouse',
        'capacity': 8000,
        'tier': 'small',
        'region': 'midwest',
    },
    'green_bay_wi': {
        'city': 'Green Bay',
        'state': 'WI',
        'latitude': 44.5133,
        'longitude': -88.0133,
        'arena': 'Resch Center',
        'capacity': 10200,
        'tier': 'small',
        'region': 'midwest',
    },
    'duluth_mn': {
        'city': 'Duluth',
        'state': 'MN',
        'latitude': 46.7867,
        'longitude': -92.1005,
        'arena': 'AMSOIL Arena',
        'capacity': 6412,
        'tier': 'small',
        'region': 'midwest',
    },
    'rapid_city_sd': {
        'city': 'Rapid City',
        'state': 'SD',
        'latitude': 44.0805,
        'longitude': -103.2310,
        'arena': 'The Monument',
        'capacity': 10000,
        'tier': 'small',
        'region': 'midwest',
    },
    'amarillo_tx': {
        'city': 'Amarillo',
        'state': 'TX',
        'latitude': 35.2220,
        'longitude': -101.8313,
        'arena': 'Civic Center Coliseum',
        'capacity': 8500,
        'tier': 'small',
        'region': 'south',
    },
    'corpus_christi_tx': {
        'city': 'Corpus Christi',
        'state': 'TX',
        'latitude': 27.8006,
        'longitude': -97.3964,
        'arena': 'American Bank Center',
        'capacity': 10500,
        'tier': 'small',
        'region': 'south',
    },
    'mobile_al': {
        'city': 'Mobile',
        'state': 'AL',
        'latitude': 30.6954,
        'longitude': -88.0399,
        'arena': 'Propst Arena',
        'capacity': 10000,
        'tier': 'small',
        'region': 'southeast',
    },
    'savannah_ga': {
        'city': 'Savannah',
        'state': 'GA',
        'latitude': 32.0835,
        'longitude': -81.0998,
        'arena': 'Enmarket Arena',
        'capacity': 9500,
        'tier': 'small',
        'region': 'southeast',
    },
    'macon_ga': {
        'city': 'Macon',
        'state': 'GA',
        'latitude': 32.8407,
        'longitude': -83.6324,
        'arena': 'Atrium Health Amphitheater',
        'capacity': 8000,
        'tier': 'small',
        'region': 'southeast',
    },
    'asheville_nc': {
        'city': 'Asheville',
        'state': 'NC',
        'latitude': 35.5951,
        'longitude': -82.5515,
        'arena': 'Harrah\'s Cherokee Center',
        'capacity': 7638,
        'tier': 'small',
        'region': 'southeast',
    },
    'chattanooga_tn': {
        'city': 'Chattanooga',
        'state': 'TN',
        'latitude': 35.0456,
        'longitude': -85.3097,
        'arena': 'McKenzie Arena',
        'capacity': 11218,
        'tier': 'small',
        'region': 'southeast',
    },
    'tri_cities_tn': {
        'city': 'Johnson City',
        'state': 'TN',
        'latitude': 36.3134,
        'longitude': -82.3535,
        'arena': 'Freedom Hall',
        'capacity': 5000,
        'tier': 'small',
        'region': 'southeast',
    },
    'montgomery_al': {
        'city': 'Montgomery',
        'state': 'AL',
        'latitude': 32.3792,
        'longitude': -86.3077,
        'arena': 'Multiplex at Cramton Bowl',
        'capacity': 6000,
        'tier': 'small',
        'region': 'southeast',
    },
    'Jonesboro_ar': {
        'city': 'Jonesboro',
        'state': 'AR',
        'latitude': 35.8423,
        'longitude': -90.7043,
        'arena': 'First National Bank Arena',
        'capacity': 10563,
        'tier': 'small',
        'region': 'south',
    },
    'hattiesburg_ms': {
        'city': 'Hattiesburg',
        'state': 'MS',
        'latitude': 31.3271,
        'longitude': -89.2903,
        'arena': 'Reed Green Coliseum',
        'capacity': 8095,
        'tier': 'small',
        'region': 'south',
    },
    'lake_charles_la': {
        'city': 'Lake Charles',
        'state': 'LA',
        'latitude': 30.2266,
        'longitude': -93.2174,
        'arena': 'Legacy Center',
        'capacity': 7500,
        'tier': 'small',
        'region': 'south',
    },
    'pueblo_co': {
        'city': 'Pueblo',
        'state': 'CO',
        'latitude': 38.2544,
        'longitude': -104.6091,
        'arena': 'Pueblo Convention Center',
        'capacity': 5000,
        'tier': 'small',
        'region': 'west',
    },
    'missoula_mt': {
        'city': 'Missoula',
        'state': 'MT',
        'latitude': 46.8721,
        'longitude': -113.9940,
        'arena': 'Adams Center',
        'capacity': 7321,
        'tier': 'small',
        'region': 'northwest',
    },
    'eugene_or': {
        'city': 'Eugene',
        'state': 'OR',
        'latitude': 44.0521,
        'longitude': -123.0868,
        'arena': 'Matthew Knight Arena',
        'capacity': 12364,
        'tier': 'small',
        'region': 'northwest',
    },
    'provo_ut': {
        'city': 'Provo',
        'state': 'UT',
        'latitude': 40.2338,
        'longitude': -111.6585,
        'arena': 'Marriott Center',
        'capacity': 18987,
        'tier': 'small',
        'region': 'west',
    },
    'santa_barbara_ca': {
        'city': 'Santa Barbara',
        'state': 'CA',
        'latitude': 34.4208,
        'longitude': -119.6982,
        'arena': 'Thunderdome',
        'capacity': 6000,
        'tier': 'small',
        'region': 'west',
    },
    'stockton_ca': {
        'city': 'Stockton',
        'state': 'CA',
        'latitude': 37.9577,
        'longitude': -121.2908,
        'arena': 'Stockton Arena',
        'capacity': 10000,
        'tier': 'small',
        'region': 'west',
    },

    # =========================================================
    # RESORT TIER
    # Destination early-season marquee events only.
    # NEVER used for: standalone neutral games, conference
    # tournaments, NCAA tournament, or any postseason event.
    # The location is the event. Capacity is irrelevant.
    # Each site has a pool of event names — one is drawn at
    # random each time the event runs that year.
    # =========================================================

    'nassau_bahamas': {
        'city': 'Nassau',
        'state': 'Bahamas',
        'latitude': 25.0480,
        'longitude': -77.3554,
        'arena': 'Imperial Arena at Atlantis',
        'capacity': 3500,
        'tier': 'resort',
        'region': 'caribbean',
        'resort_only': True,
        'event_names': [
            'Battle 4 Atlantis',
            'Nassau Championship',
            'Atlantis Classic',
            'Paradise Shootout',
            'Bahamas Invitational',
        ],
    },
    'paradise_island_bahamas': {
        'city': 'Paradise Island',
        'state': 'Bahamas',
        'latitude': 25.0865,
        'longitude': -77.3212,
        'arena': 'Atlantis Resort Convention Centre',
        'capacity': 3000,
        'tier': 'resort',
        'region': 'caribbean',
        'resort_only': True,
        'event_names': [
            'Paradise Island Classic',
            'The Atlantis Invitational',
            'Paradise Tip-Off',
            'Island Championship',
            'Bahamas Basketball Festival',
        ],
    },
    'cancun_mexico': {
        'city': 'Cancun',
        'state': 'Mexico',
        'latitude': 21.1619,
        'longitude': -86.8515,
        'arena': 'Moon Palace Arena',
        'capacity': 5000,
        'tier': 'resort',
        'region': 'caribbean',
        'resort_only': True,
        'event_names': [
            'Cancun Challenge',
            'Mexico Tip-Off',
            'Moon Palace Classic',
            'Riviera Maya Invitational',
            'The Cancun Classic',
        ],
    },
    'san_juan_pr': {
        'city': 'San Juan',
        'state': 'Puerto Rico',
        'latitude': 18.4655,
        'longitude': -66.1057,
        'arena': 'Coliseo de Puerto Rico',
        'capacity': 18000,
        'tier': 'resort',
        'region': 'caribbean',
        'resort_only': True,
        'event_names': [
            'Puerto Rico Tip-Off',
            'San Juan Invitational',
            'Caribbean Classic',
            'El Morro Shootout',
            'Island Showdown',
        ],
    },
    'maui_hi': {
        'city': 'Lahaina',
        'state': 'Hawaii',
        'latitude': 20.8783,
        'longitude': -156.6825,
        'arena': 'Lahaina Civic Center',
        'capacity': 2500,
        'tier': 'resort',
        'region': 'pacific',
        'resort_only': True,
        'event_names': [
            'Maui Invitational',
            'Aloha Classic',
            'Maui Jim Classic',
            'Valley Isle Tip-Off',
            'The Maui',
        ],
    },
    'honolulu_hi': {
        'city': 'Honolulu',
        'state': 'Hawaii',
        'latitude': 21.3069,
        'longitude': -157.8583,
        'arena': 'SimpliFi Arena at Stan Sheriff Center',
        'capacity': 10300,
        'tier': 'resort',
        'region': 'pacific',
        'resort_only': True,
        'event_names': [
            'Diamond Head Classic',
            'Honolulu Invitational',
            'Aloha Tip-Off',
            'Hawaii Championship',
            'Pacific Classic',
        ],
    },
    'key_west_fl': {
        'city': 'Key West',
        'state': 'FL',
        'latitude': 24.5551,
        'longitude': -81.7800,
        'arena': 'Harvey Government Center',
        'capacity': 2000,
        'tier': 'resort',
        'region': 'caribbean',
        'resort_only': True,
        'event_names': [
            'Key West Invitational',
            'Southernmost Classic',
            'Conch Republic Shootout',
            'The Key West',
            'Duval Street Classic',
        ],
    },
    'punta_cana_dr': {
        'city': 'Punta Cana',
        'state': 'Dominican Republic',
        'latitude': 18.5820,
        'longitude': -68.4055,
        'arena': 'Hard Rock Hotel Arena',
        'capacity': 4000,
        'tier': 'resort',
        'region': 'caribbean',
        'resort_only': True,
        'event_names': [
            'Punta Cana Classic',
            'Hard Rock Invitational',
            'Dominican Tip-Off',
            'Caribbean Shootout',
            'The Punta Cana Challenge',
        ],
    },
    'montego_bay_jamaica': {
        'city': 'Montego Bay',
        'state': 'Jamaica',
        'latitude': 18.4762,
        'longitude': -77.8939,
        'arena': 'Montego Bay Convention Centre',
        'capacity': 3500,
        'tier': 'resort',
        'region': 'caribbean',
        'resort_only': True,
        'event_names': [
            'Jamaica Classic',
            'Montego Bay Invitational',
            'Reggae Shootout',
            'Island Tip-Off',
            'The Jamaica Challenge',
        ],
    },
    'aruba': {
        'city': 'Oranjestad',
        'state': 'Aruba',
        'latitude': 12.5092,
        'longitude': -70.0086,
        'arena': 'Aruba Entertainment Center',
        'capacity': 3000,
        'tier': 'resort',
        'region': 'caribbean',
        'resort_only': True,
        'event_names': [
            'Aruba Classic',
            'One Happy Island Invitational',
            'Caribbean Sun Classic',
            'The Aruba Shootout',
            'Island Championship',
        ],
    },
    'st_thomas_usvi': {
        'city': 'Charlotte Amalie',
        'state': 'U.S. Virgin Islands',
        'latitude': 18.3419,
        'longitude': -64.9307,
        'arena': 'Lionel Roberts Stadium',
        'capacity': 2800,
        'tier': 'resort',
        'region': 'caribbean',
        'resort_only': True,
        'event_names': [
            'Virgin Islands Classic',
            'St. Thomas Invitational',
            'Caribbean Tip-Off',
            'Trade Winds Classic',
            'The USVI Shootout',
        ],
    },
    'cayman_islands': {
        'city': 'George Town',
        'state': 'Cayman Islands',
        'latitude': 19.2869,
        'longitude': -81.3674,
        'arena': 'John Gray Gymnasium',
        'capacity': 2500,
        'tier': 'resort',
        'region': 'caribbean',
        'resort_only': True,
        'event_names': [
            'Cayman Classic',
            'Grand Cayman Invitational',
            'Seven Mile Beach Shootout',
            'The Cayman Challenge',
            'Island Hoops Classic',
        ],
    },
    'cabo_san_lucas_mx': {
        'city': 'Cabo San Lucas',
        'state': 'Mexico',
        'latitude': 22.8905,
        'longitude': -109.9167,
        'arena': 'Centro de Usos Multiples',
        'capacity': 3000,
        'tier': 'resort',
        'region': 'caribbean',
        'resort_only': True,
        'event_names': [
            'Cabo Classic',
            'Land\'s End Invitational',
            'Baja Tip-Off',
            'The Cabo Shootout',
            'Sea of Cortez Classic',
        ],
    },
    'riviera_maya_mx': {
        'city': 'Playa del Carmen',
        'state': 'Mexico',
        'latitude': 20.6296,
        'longitude': -87.0739,
        'arena': 'Barcelo Maya Arena',
        'capacity': 3500,
        'tier': 'resort',
        'region': 'caribbean',
        'resort_only': True,
        'event_names': [
            'Riviera Maya Classic',
            'Playa del Carmen Invitational',
            'Mayan Riviera Shootout',
            'The Riviera Challenge',
            'Tulum Classic',
        ],
    },
    'bermuda': {
        'city': 'Hamilton',
        'state': 'Bermuda',
        'latitude': 32.2945,
        'longitude': -64.7839,
        'arena': 'National Sports Centre',
        'capacity': 3000,
        'tier': 'resort',
        'region': 'caribbean',
        'resort_only': True,
        'event_names': [
            'Bermuda Classic',
            'Pink Sand Invitational',
            'Atlantic Shootout',
            'The Bermuda Challenge',
            'Hamilton Classic',
        ],
    },
}


def get_sites_by_tier(tier):
    """Return list of (key, dict) tuples for a given tier."""
    return [(k, s) for k, s in NEUTRAL_SITES.items() if s['tier'] == tier]


def get_sites_by_region(region):
    """Return list of (key, dict) tuples for a given region."""
    return [(k, s) for k, s in NEUTRAL_SITES.items() if s['region'] == region]


def get_site(site_key):
    """Return a neutral site dict by key."""
    return NEUTRAL_SITES.get(site_key)


def get_resort_sites():
    """
    Return all resort-tier sites.
    These are eligible ONLY for early-season marquee destination events.
    Never used for: standalone neutral games, conference tournaments,
    NCAA tournament, or any postseason context.
    """
    return [(k, s) for k, s in NEUTRAL_SITES.items() if s['tier'] == 'resort']


def is_warm_weather(site_key):
    """
    Returns True if a site is warm-weather eligible.
    Derived from latitude -- anything below 32 degrees north qualifies.
    Resort sites are always warm weather by definition.
    """
    site = NEUTRAL_SITES.get(site_key)
    if not site:
        return False
    if site['tier'] == 'resort':
        return True
    return site['latitude'] < 32.0


def is_resort_only(site_key):
    """
    Returns True if a site is restricted to resort marquee events only.
    These sites must never appear in any other scheduling context.
    """
    site = NEUTRAL_SITES.get(site_key)
    if not site:
        return False
    return site.get('resort_only', False)


def get_event_name(site_key, rng=None):
    """
    Draw a random event name for a resort site.
    Pass an optional random.Random instance for reproducibility.
    Falls back to city name + 'Classic' if no event_names defined.
    """
    import random as _random
    site = NEUTRAL_SITES.get(site_key)
    if not site:
        return 'Classic'
    names = site.get('event_names', [])
    if not names:
        return site.get('city', 'Unknown') + ' Classic'
    picker = rng if rng else _random
    return picker.choice(names)


def get_schedulable_sites():
    """
    Return all sites eligible for standard scheduling
    (standalone neutral games, conference tournaments, NCAA tournament).
    Excludes resort-only sites entirely.
    """
    return [(k, s) for k, s in NEUTRAL_SITES.items()
            if not s.get('resort_only', False)]
